import type {
  Incident,
  MeshNode,
  MeshConnection,
  NetworkStats,
  RawMessage,
} from "./types";

export const mockRawMessages: RawMessage[] = [
  {
    id: "raw-1",
    content:
      "URGENT: Road blocked near central hospital, need alternative route immediately!",
    source: "telegram",
    timestamp: Date.now() - 120000,
    author: "Anonymous_42",
    hasImage: true,
    imageUrl: "/placeholder-crisis-1.jpg",
    location: { lat: 31.5, lng: 34.47 },
    isProcessing: false,
  },
  {
    id: "raw-2",
    content: "Water distribution point at school building - unverified",
    source: "whatsapp",
    timestamp: Date.now() - 300000,
    author: "+97254*****",
    hasImage: false,
    isProcessing: true,
  },
  {
    id: "raw-3",
    content:
      "Medical supplies needed at refugee camp sector B, critical shortage of insulin",
    source: "telegram",
    timestamp: Date.now() - 60000,
    author: "MedAid_Volunteer",
    hasImage: true,
    imageUrl: "/placeholder-crisis-2.jpg",
    location: { lat: 31.52, lng: 34.45 },
    isProcessing: false,
  },
  {
    id: "raw-4",
    content:
      "WARNING: Suspicious checkpoint reported on northern highway - avoid!",
    source: "telegram",
    timestamp: Date.now() - 180000,
    author: "SafeRoute_Bot",
    hasImage: false,
    location: { lat: 31.55, lng: 34.5 },
    isProcessing: false,
  },
  {
    id: "raw-5",
    content: "Family of 6 trapped in collapsed building, sending coordinates",
    source: "whatsapp",
    timestamp: Date.now() - 30000,
    author: "+97250*****",
    hasImage: true,
    imageUrl: "/placeholder-crisis-3.jpg",
    location: { lat: 31.48, lng: 34.42 },
    isProcessing: false,
  },
];

export const mockIncidents: Incident[] = [
  {
    id: "inc-1",
    title: "Road Blockage - Central Hospital Access",
    description:
      "Main access road to central hospital completely blocked by debris. Alternative routes via Eastern bypass recommended.",
    location: { lat: 31.5, lng: 34.47, address: "Al-Rashid Street, Block 7" },
    status: "verified",
    severity: "critical",
    category: "infrastructure",
    imageUrl: "/placeholder-verified-1.jpg",
    source: {
      type: "telegram",
      userId: "user_123",
      authorityScore: 75,
    },
    verification: {
      score: 92,
      status: "verified",
      checks: [
        {
          type: "reverse_image",
          passed: true,
          confidence: 95,
          details: "No historical matches found",
        },
        {
          type: "geolocation",
          passed: true,
          confidence: 88,
          details: "EXIF matches claimed location",
        },
        {
          type: "temporal",
          passed: true,
          confidence: 90,
          details: "Shadow analysis confirms current time",
        },
        { type: "peer_confirm", passed: true, confidence: 100, details: "5 mesh confirmations" },
      ],
      timestamp: Date.now() - 100000,
    },
    timestamp: Date.now() - 120000,
    updatedAt: Date.now() - 50000,
    peerConfirmations: 5,
  },
  {
    id: "inc-2",
    title: "Medical Supply Shortage - Sector B",
    description:
      "Critical shortage of insulin and basic medical supplies at refugee camp sector B. Immediate resupply required.",
    location: { lat: 31.52, lng: 34.45, address: "Refugee Camp, Sector B" },
    status: "verified",
    severity: "critical",
    category: "medical",
    source: {
      type: "direct",
      userId: "ngo_medaid",
      authorityScore: 95,
    },
    verification: {
      score: 88,
      status: "verified",
      checks: [
        {
          type: "reverse_image",
          passed: true,
          confidence: 100,
          details: "Original photo",
        },
        {
          type: "geolocation",
          passed: true,
          confidence: 85,
          details: "Location verified",
        },
        {
          type: "peer_confirm",
          passed: true,
          confidence: 90,
          details: "3 NGO confirmations",
        },
      ],
      timestamp: Date.now() - 50000,
    },
    timestamp: Date.now() - 60000,
    updatedAt: Date.now() - 30000,
    peerConfirmations: 3,
  },
  {
    id: "inc-3",
    title: "Suspicious Checkpoint - Northern Highway",
    description:
      "Unverified reports of suspicious checkpoint on northern highway. Exercise extreme caution.",
    location: { lat: 31.55, lng: 34.5, address: "Northern Highway, KM 12" },
    status: "unconfirmed",
    severity: "high",
    category: "security",
    source: {
      type: "telegram",
      authorityScore: 40,
    },
    verification: {
      score: 45,
      status: "unconfirmed",
      checks: [
        {
          type: "reverse_image",
          passed: false,
          confidence: 0,
          details: "No image provided",
        },
        {
          type: "geolocation",
          passed: true,
          confidence: 60,
          details: "Approximate location",
        },
        {
          type: "peer_confirm",
          passed: false,
          confidence: 30,
          details: "1 unverified report",
        },
      ],
      timestamp: Date.now() - 170000,
    },
    timestamp: Date.now() - 180000,
    updatedAt: Date.now() - 170000,
    peerConfirmations: 1,
  },
  {
    id: "inc-4",
    title: "Water Distribution Active",
    description:
      "Clean water distribution point operational at school building. Capacity: 500 families/day.",
    location: { lat: 31.49, lng: 34.46, address: "Al-Nour School" },
    status: "resolved",
    severity: "medium",
    category: "water",
    source: {
      type: "direct",
      userId: "unicef_field",
      authorityScore: 98,
    },
    verification: {
      score: 95,
      status: "verified",
      checks: [
        { type: "reverse_image", passed: true, confidence: 100 },
        { type: "geolocation", passed: true, confidence: 98 },
        { type: "peer_confirm", passed: true, confidence: 100, details: "NGO verified" },
      ],
      timestamp: Date.now() - 3600000,
    },
    timestamp: Date.now() - 3700000,
    updatedAt: Date.now() - 1800000,
    peerConfirmations: 12,
  },
  {
    id: "inc-5",
    title: "Trapped Family - Building Collapse",
    description:
      "Family of 6 reported trapped in collapsed residential building. Rescue teams dispatched.",
    location: { lat: 31.48, lng: 34.42, address: "Block 15, Building 7" },
    status: "verified",
    severity: "critical",
    category: "evacuation",
    imageUrl: "/placeholder-verified-2.jpg",
    source: {
      type: "whatsapp",
      authorityScore: 60,
    },
    verification: {
      score: 78,
      status: "verified",
      checks: [
        { type: "reverse_image", passed: true, confidence: 85 },
        { type: "geolocation", passed: true, confidence: 75 },
        { type: "satellite", passed: true, confidence: 80, details: "Building damage confirmed" },
        { type: "peer_confirm", passed: true, confidence: 70, details: "2 confirmations" },
      ],
      timestamp: Date.now() - 25000,
    },
    timestamp: Date.now() - 30000,
    updatedAt: Date.now() - 20000,
    peerConfirmations: 2,
  },
];

export const mockMeshNodes: MeshNode[] = [
  {
    id: "node-1",
    type: "phone",
    status: "online",
    signalStrength: 95,
    position: { x: 200, y: 150 },
    connections: ["node-2", "node-3", "node-bridge"],
    lastSeen: Date.now(),
    hopCount: 0,
  },
  {
    id: "node-2",
    type: "phone",
    status: "online",
    signalStrength: 82,
    position: { x: 350, y: 120 },
    connections: ["node-1", "node-4"],
    lastSeen: Date.now() - 5000,
    hopCount: 1,
  },
  {
    id: "node-3",
    type: "phone",
    status: "weak",
    signalStrength: 45,
    position: { x: 150, y: 280 },
    connections: ["node-1", "node-5"],
    lastSeen: Date.now() - 30000,
    hopCount: 1,
  },
  {
    id: "node-4",
    type: "phone",
    status: "online",
    signalStrength: 78,
    position: { x: 480, y: 200 },
    connections: ["node-2", "node-bridge"],
    lastSeen: Date.now() - 2000,
    hopCount: 2,
  },
  {
    id: "node-5",
    type: "lora",
    status: "online",
    signalStrength: 88,
    position: { x: 100, y: 380 },
    connections: ["node-3", "node-6"],
    lastSeen: Date.now() - 1000,
    hopCount: 2,
  },
  {
    id: "node-6",
    type: "phone",
    status: "offline",
    signalStrength: 0,
    position: { x: 50, y: 450 },
    connections: [],
    lastSeen: Date.now() - 120000,
    hopCount: 3,
  },
  {
    id: "node-bridge",
    type: "bridge",
    status: "online",
    signalStrength: 100,
    position: { x: 400, y: 300 },
    connections: ["node-1", "node-4", "node-7"],
    lastSeen: Date.now(),
    hopCount: 0,
  },
  {
    id: "node-7",
    type: "phone",
    status: "weak",
    signalStrength: 35,
    position: { x: 520, y: 380 },
    connections: ["node-bridge"],
    lastSeen: Date.now() - 45000,
    hopCount: 1,
  },
];

export const mockMeshConnections: MeshConnection[] = [
  { source: "node-1", target: "node-2", strength: 85, latency: 45 },
  { source: "node-1", target: "node-3", strength: 55, latency: 120 },
  { source: "node-1", target: "node-bridge", strength: 95, latency: 20 },
  { source: "node-2", target: "node-4", strength: 75, latency: 65 },
  { source: "node-3", target: "node-5", strength: 60, latency: 150 },
  { source: "node-4", target: "node-bridge", strength: 80, latency: 55 },
  { source: "node-5", target: "node-6", strength: 0, latency: 9999 },
  { source: "node-bridge", target: "node-7", strength: 40, latency: 200 },
];

export const mockNetworkStats: NetworkStats = {
  totalNodes: 8,
  onlineNodes: 5,
  avgLatency: 95,
  syncStatus: "synced",
  lastSync: Date.now() - 5000,
};
